local PROTO = {
  ["Fight_one_shownumber"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="type",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="value",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="optional",
          ["attrName"]="hurt_type",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="optional",
          ["attrName"]="hurt_type2",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_shownumber_protect"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="ori_tar_id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="now_tar_id",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="repeated",
          ["attrName"]="sinfo",
          ["aType"]="Fight_one_shownumber",
        },
    },
  ["S2c_chat_system"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="type",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="msg",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="optional",
          ["attrName"]="extdata",
          ["aType"]="string",
        },
    },
  ["S2c_fight_die"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
    },
  ["Boxoffice_oneinfo"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="rank",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="name",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="grade",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="sex",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="required",
          ["attrName"]="score",
          ["aType"]="int32",
        },
    },
  ["S2c_role_info_string_r"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="info",
          ["aType"]="Role_info_string",
        },
    },
  ["C2s_test_int32"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="test",
          ["aType"]="int32",
        },
    },
  ["Fight_warrior_prop"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="name",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="shape",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="warrior_type",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="required",
          ["attrName"]="camp_type",
          ["aType"]="int32",
        },
      [6]=
        {
          ["sType"]="required",
          ["attrName"]="pos",
          ["aType"]="int32",
        },
      [7]=
        {
          ["sType"]="required",
          ["attrName"]="hp",
          ["aType"]="int32",
        },
      [8]=
        {
          ["sType"]="required",
          ["attrName"]="hpmax",
          ["aType"]="int32",
        },
      [9]=
        {
          ["sType"]="optional",
          ["attrName"]="owner_id",
          ["aType"]="string",
        },
    },
  ["S2c_login_serverinfo"]=
    {
      [1]=
        {
          ["sType"]="optional",
          ["attrName"]="ip",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="port",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="secret",
          ["aType"]="string",
        },
    },
  ["Fight_one_strategicpoint"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="isuse",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="lock_state",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_strategicpoint"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="spoint_info",
          ["aType"]="Fight_one_strategicpoint",
        },
    },
  ["S2c_fight_addbuff"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="buff_id",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="buff_lv",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="cont_type",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="required",
          ["attrName"]="c_round",
          ["aType"]="int32",
        },
    },
  ["C2s_fight_cmd_finish"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="place_holder",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_hit"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="att_id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="main_tar_id",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="repeated",
          ["attrName"]="tar_ids",
          ["aType"]="string",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="skill_id",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="required",
          ["attrName"]="move_to_t",
          ["aType"]="int32",
        },
      [6]=
        {
          ["sType"]="required",
          ["attrName"]="move_bk_t",
          ["aType"]="int32",
        },
      [7]=
        {
          ["sType"]="required",
          ["attrName"]="hit_time",
          ["aType"]="int32",
        },
    },
  ["S2c_chat_speak"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="channel",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="chat_msg",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="uid",
          ["aType"]="string",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="photo",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="required",
          ["attrName"]="name",
          ["aType"]="string",
        },
    },
  ["S2c_item_setamount"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="frameno",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="amount",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_cmd_begin"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="uid",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="left_time",
          ["aType"]="int32",
        },
    },
  ["S2s_mainserver_test"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="info",
          ["aType"]="string",
        },
    },
  ["Test_info1"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="info1",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_reset_hpmax"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="hpmap",
          ["aType"]="int32",
        },
    },
  ["Fight_one_playerinfo"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="uid",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="name",
          ["aType"]="string",
        },
    },
  ["C2s_wizcmd"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="wizcmd",
          ["aType"]="string",
        },
    },
  ["C2s_chat_private"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="dst_uid",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="chat_msg",
          ["aType"]="string",
        },
    },
  ["S2c_fight_delbuff"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="buff_id",
          ["aType"]="int32",
        },
    },
  ["S2c_login_c2gateserver"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="place_holder",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_shownumber"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="type",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="value",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="optional",
          ["attrName"]="hurt_type",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="optional",
          ["attrName"]="hurt_type2",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_actor"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="actor_id",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="state",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_resetbuff"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="buff_id",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="buff_lv",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="cont_type",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="required",
          ["attrName"]="c_round",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_miss"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="att_id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="miss_id",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="miss_time",
          ["aType"]="int32",
        },
    },
  ["S2c_item_frame"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="frameno",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="repeated",
          ["attrName"]="iinfo",
          ["aType"]="Item_info",
        },
    },
  ["S2c_role_info_int_r"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="info",
          ["aType"]="Role_info_int",
        },
    },
  ["C2s_fight_actor_drawend"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="actor_id",
          ["aType"]="int32",
        },
    },
  ["S2c_test_string"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="test",
          ["aType"]="string",
        },
    },
  ["C2s_fight_leave"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="place_holder",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_rehit"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="att_id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="tar_id",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="skill_id",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="hit_time",
          ["aType"]="int32",
        },
    },
  ["C2s_boxoffice_getreward"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="place_holder",
          ["aType"]="int32",
        },
    },
  ["S2c_role_info_string"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="key",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="optional",
          ["attrName"]="value",
          ["aType"]="string",
        },
    },
  ["S2c_fight_shownumber_r"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="sinfo",
          ["aType"]="Fight_one_shownumber",
        },
    },
  ["S2c_fight_end"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="whowin",
          ["aType"]="int32",
        },
    },
  ["Item_info"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="itemno",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="amount",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="isbind",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_upgradeskill"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="old_skillid",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="new_skillid",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="lv",
          ["aType"]="int32",
        },
    },
  ["S2c_test_float"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="test",
          ["aType"]="float",
        },
    },
  ["C2s_fight_test"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="place_holder",
          ["aType"]="int32",
        },
    },
  ["S2c_test_int32"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="test",
          ["aType"]="int32",
        },
    },
  ["S2c_test_int64"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="test",
          ["aType"]="int64",
        },
    },
  ["C2s_chat_speak"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="channel",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="chat_msg",
          ["aType"]="string",
        },
    },
  ["S2c_fight_strategic_hit"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="att_uid",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="main_tar_id",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="repeated",
          ["attrName"]="tar_ids",
          ["aType"]="string",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="skill_id",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="required",
          ["attrName"]="hit_time",
          ["aType"]="int32",
        },
    },
  ["C2s_test_float"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="test",
          ["aType"]="float",
        },
    },
  ["S2c_item_add"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="frameno",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="info",
          ["aType"]="Item_info",
        },
    },
  ["C2s_test_string"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="test",
          ["aType"]="string",
        },
    },
  ["C2s_boxoffice_rankinfo"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="rank",
          ["aType"]="int32",
        },
    },
  ["S2c_item_del"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="frameno",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
    },
  ["C2s_login_c2gateserver"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="acct",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="corp_id",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="server_id",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="sign",
          ["aType"]="string",
        },
    },
  ["S2c_fight_skillcd"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="skill_id",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="cd",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_leave"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
    },
  ["S2c_login_player_name"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="exist",
          ["aType"]="int32",
        },
    },
  ["Role_info_string"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="key",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="optional",
          ["attrName"]="value",
          ["aType"]="string",
        },
    },
  ["C2s_fight_cmd"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="skill_id",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="tar_id",
          ["aType"]="string",
        },
    },
  ["Role_info_int"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="key",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="optional",
          ["attrName"]="value",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_changeweather"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="weather_no",
          ["aType"]="int32",
        },
    },
  ["S2c_role_info_int"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="key",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="optional",
          ["attrName"]="value",
          ["aType"]="int32",
        },
    },
  ["S2c_test_info"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="info3",
          ["aType"]="Test_info2",
        },
    },
  ["S2c_fight_bout"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="bout_count",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="state",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_cmd_end"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="place_holder",
          ["aType"]="int32",
        },
    },
  ["Fight_skill"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="skill_id",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="lv",
          ["aType"]="int32",
        },
    },
  ["C2s_login_player_enter"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="uid",
          ["aType"]="string",
        },
    },
  ["S2c_fight_addskill"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="skill_id",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="lv",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_strategic_actor"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="uid",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="actor_id",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="state",
          ["aType"]="int32",
        },
    },
  ["S2c_fight_addwarrior"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="warriorp",
          ["aType"]="Fight_warrior_prop",
        },
    },
  ["S2c_fight_relive"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
    },
  ["C2s_login_player_name"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="name",
          ["aType"]="string",
        },
    },
  ["C2s_login_corp_account"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="corp_id",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="server_id",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="acct",
          ["aType"]="string",
        },
      [4]=
        {
          ["sType"]="required",
          ["attrName"]="adult",
          ["aType"]="int32",
        },
      [5]=
        {
          ["sType"]="required",
          ["attrName"]="login_time",
          ["aType"]="int32",
        },
      [6]=
        {
          ["sType"]="required",
          ["attrName"]="sign",
          ["aType"]="string",
        },
    },
  ["C2s_login_player_add"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="name",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="role_no",
          ["aType"]="int32",
        },
    },
  ["S2c_login_playerlist"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="pinfos",
          ["aType"]="Login_playerinfo",
        },
    },
  ["S2c_fight_delskill"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="skill_id",
          ["aType"]="int32",
        },
    },
  ["S2c_login_error"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="err_no",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="err_desc",
          ["aType"]="string",
        },
    },
  ["C2s_item_use"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="frameno",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="cnt",
          ["aType"]="int32",
        },
    },
  ["C2s_item_frame"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="frameno",
          ["aType"]="int32",
        },
    },
  ["S2c_boxoffice_rankinfo"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="rinfo",
          ["aType"]="Boxoffice_oneinfo",
        },
    },
  ["S2c_fight_start"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="war_type",
          ["aType"]="int32",
        },
      [2]=
        {
          ["sType"]="optional",
          ["attrName"]="scene_id",
          ["aType"]="int32",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="camp_type",
          ["aType"]="int32",
        },
      [4]=
        {
          ["sType"]="repeated",
          ["attrName"]="fskill",
          ["aType"]="Fight_skill",
        },
      [5]=
        {
          ["sType"]="repeated",
          ["attrName"]="warriorp",
          ["aType"]="Fight_warrior_prop",
        },
      [6]=
        {
          ["sType"]="required",
          ["attrName"]="self_uid",
          ["aType"]="string",
        },
      [7]=
        {
          ["sType"]="repeated",
          ["attrName"]="pinfo",
          ["aType"]="Fight_one_playerinfo",
        },
      [8]=
        {
          ["sType"]="required",
          ["attrName"]="enter_scenetime",
          ["aType"]="int32",
        },
      [9]=
        {
          ["sType"]="required",
          ["attrName"]="acter_id",
          ["aType"]="int32",
        },
    },
  ["C2s_test_int64"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="test",
          ["aType"]="int64",
        },
    },
  ["S2c_fight_chat"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="id",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="msg",
          ["aType"]="string",
        },
    },
  ["Test_info2"]=
    {
      [1]=
        {
          ["sType"]="repeated",
          ["attrName"]="info2",
          ["aType"]="Test_info1",
        },
    },
  ["Login_playerinfo"]=
    {
      [1]=
        {
          ["sType"]="required",
          ["attrName"]="uid",
          ["aType"]="string",
        },
      [2]=
        {
          ["sType"]="required",
          ["attrName"]="name",
          ["aType"]="string",
        },
      [3]=
        {
          ["sType"]="required",
          ["attrName"]="grade",
          ["aType"]="int32",
        },
    },
}

return PROTO
