--Buildin Table
Protocal = {
	Connect			= '101';	--连接服务器
	Exception   	= '102';	--异常掉线
	Disconnect  	= '103';	--正常断线   
	Message			= '104';	--接收消息
	Reconnected 	= '105'; 	--重连服务器
	BeginReconnect 	= '106'; 	--正在重连服务器
	KickOut 		= '107'; 	--被服务器踢下线
	PingUpdate 		= '108'; 	--检测ping值
	AccConflict 	= '109'; 	--被顶号
	HeartBeat 		= '110'; 	--发送心跳给服务器
	WeakMessage 	= '111';	--弱优先级消息处理	
}


EventName = {
	-------------------------组队------------------------------
	TEAM_MEMBER_UPDATE = "TEAM_MEMBER_UPDATE";
	NEARBY_TEAM_UPDATE = "NEARBY_TEAM_UPDATE";
	TEAM_SETTING_UPDATE = "TEAM_SETTING_UPDATE";
	INVITATION_DATA_UPDATE = "INVITATION_DATA_UPDATE";			--邀请数据更新
	TEAM_INVITE_CHECK = "TEAM_INVITE_CHECK";
	TEAM_LEADER_CHECK = "TEAM_LEADER_CHECK";
	TEAM_SYNC_HP = "TEAM_SYNC_HP";
	TEAM_APPLY_EVENT = "TEAM_APPLY_EVENT";
	------------------------Common------------------------------
	CLOSE_WINDOW_EVENT = "CLOSE_WINDOW_EVENT";					--关闭弹窗事件
	UPDATE_PANEL_EVENT = "UPDATE_PANEL_EVENT";					--面板刷新事件
	FIGHT_READY_TIPS_EVENT = "FIGHT_READY_TIPS_EVENT";			--准备战斗提示
	COLLECT_STATE_EVENT = "COLLECT_STATE_EVENT";				--采集状态事件
	COLLECT_CLICK_SHOW = "COLLECT_CLICK_SHOW";					--采集点击事件
	COLLECT_SHOW_EVENT = "COLLECT_SHOW_EVENT";					--采集显示事件
	COLLECT_HIDE_EVENT = "COLLECT_HIDE_EVENT";					--采集隐藏事件
	RUNE_SHOW_EVENT = "RUNE_SHOW_EVENT";						--符文显示事件
	RUNE_HIDE_EVENT = "RUNE_HIDE_EVENT";						--符文隐藏事件
	RUNE_CLICK_EVENT = "RUNE_CLICK_EVENT";						--符文点击事件
	MARRIAGE_STATE = "MARRIAGE_STATE";
	DISCONNECT_AND_RECONNECT = "DISCONNECT_AND_RECONNECT";		--断线重连
	ITEM_BUY_EVENT = "ITEM_BUY_EVENT";							--购买物品回调
	ITEM_USE_EVENT = "ITEM_USE_EVENT";			--物品使用改变事件

	--------------------------帮派首领--------------------------------
	FACTION_BOSS_INFO_UPDATE = "FACTION_BOSS_INFO_UPDATE";
	FACTION_BOSS_RANK_UPDATE = "FACTION_BOSS_RANK_UPDATE";
	FACTION_BOSS_OUTPUT_INFO = "FACTION_BOSS_OUTPUT_INFO";
	FACTION_BOSS_ADD_EXP = "FACTION_BOSS_ADD_EXP";
	FACTION_BOSS_CALL_EVENT = "FACTION_BOSS_CALL_EVENT";
	FACTION_BOSS_CLOSE_EXP = "FACTION_BOSS_CLOSE_EXP";
	FACTION_BOSS_NPC = "FACTION_BOSS_NPC";
	--------------------------帮派强盗--------------------------------
	FACTION_THIEVES_COUNT = "FACTION_THIEVES_COUNT";
	FACTION_THIEVES_RESULT = "FACTION_THIEVES_RESULT";
	---------------------------帮派争霸-------------------------------
	FACTION_WAR_INFO = "FACTION_WAR_INFO";
	FACTION_WAR_RANK_UPDATE = "FACTION_WAR_RANK_UPDATE";
	FACTION_WAR_INTEGRAL_RANK = "FACTION_WAR_INTEGRAL_RANK";	--帮派积分排名（前五）
	FACTION_WAR_BOSS_INFO = "FACTION_WAR_BOSS_INFO";
	FACTION_WAR_FACTION_INTEGRAL = "FACTION_WAR_FACTION_INTEGRAL";  --帮派积分
	FACTION_WAR_INTEGRAL = "FACTION_WAR_INTEGRAL";					--个人积分
	FACTION_WAR_DETAIL_INFO = "FACTION_WAR_DETAIL_INFO";
	FACTION_WAR_SELF_RANK = "FACTION_WAR_SELF_RANK";
	FACTION_WAR_SELF_RANK_GET = "FACTION_WAR_SELF_RANK_GET";
	-------------------------------帮派红包-------------------------------
	FACTION_LUCKY_MONEY_MAIN_UI = "FACTION_LUCKY_MONEY_MAIN_UI";
	FACTION_LUCKY_MONEY_RECEIVE = "FACTION_LUCKY_MONEY_RECEIVE";
	FACTION_LUCKY_MONEY_OWN = "FACTION_LUCKY_MONEY_OWN";
	FACTION_LUCKY_MONEY_ROD = "FACTION_LUCKY_MONEY_ROD";
	FACTION_LUCKY_MONEY_HISTORY = "FACTION_LUCKY_MONEY_HISTORY";
	FACTION_LUCKY_MONEY_SEND_WINDOW = "FACTION_LUCKY_MONEY_SEND_WINDOW";
	FACTION_LUCKY_MONEY_RECHARGE = "FACTION_LUCKY_MONEY_RECHARGE";
	FACTION_LUCKY_MONEY_REMOVE = "FACTION_LUCKY_MONEY_REMOVE";
	FACTION_LUCKY_MONEY_STATE = "FACTION_LUCKY_MONEY_STATE";
	-------------------------------帮派传功--------------------------------
	FACTION_TRANSMIT_TO_NPC = "FACTION_TRANSMIT_TO_NPC";
	FACTION_TRANSMIT_MEMBERS_LIST = "FACTION_TRANSMIT_MEMBERS_LIST";
	FACTION_TRANSMIT_PROGRESS_OPEN = "FACTION_TRANSMIT_PROGRESS_OPEN";
	FACTION_TRANSMIT_PROGRESS_CLOSE = "FACTION_TRANSMIT_PROGRESS_CLOSE";
	FACTION_TRANSMIT_INITIATIVE_INVITATION = "FACTION_TRANSMIT_INITIATIVE_INVITATION";
	FACTION_TRANSMIT_PASSIVITY_INVITATION = "FACTION_TRANSMIT_PASSIVITY_INVITATION";
	FACTION_TRANSMIT_INITIATIVE_REFUSE = "FACTION_TRANSMIT_INITIATIVE_REFUSE";
	FACTION_TRANSMIT_PASSIVITY_REFUSE = "FACTION_TRANSMIT_PASSIVITY_REFUSE";
	-------------------------------商城----------------------------------
	SHOP_ITEM_UPDATE = "SHOP_ITEM_UPDATE";
	SHOP_ITEM_BUY_EVENT = "SHOP_ITEM_BUY_EVENT";
	SHOP_GIVE_FRIEND_EVENT = "SHOP_GIVE_FRIEND_EVENT";

	-------------------------------多人副本-----------------------------------
	MULTICOPY_UPDATE_EVENT = "MULTICOPY_UPDATE_EVENT";
	MULTICOPY_RANK_UPDATE = "MULTICOPY_RANK_UPDATE";
	MULTICOPY_PASS_INFO = "MULTICOPY_PASS_INFO";

	---------------------------------房间队伍----------------------------------
	ROOM_TEAM_TYPE_LIST = "ROOM_TEAM_TYPE_LIST";	--同类型的房间队伍
	ROOM_TEAM_MY_TEAM_UPDATE = "ROOM_TEAM_MY_TEAM_UPDATE";
	ROOM_TEAM_LEAVE = "ROOM_TEAM_LEAVE";
	ROOM_TEAM_INVITION_EVENT = "ROOM_TEAM_INVITION_EVENT";
	ROOM_TEAM_INVITE_EVENT = "ROOM_TEAM_INVITE_EVENT";
	ROOM_TEAM_CONFIRM_INVITE = "ROOM_TEAM_CONFIRM_INVITE";
	ROOM_TEAM_STATE = "ROOM_TEAM_STATE";
	ROOM_TEAM_INVITE_COOL_TIME = "ROOM_TEAM_INVITE_COOL_TIME";
	-------------------------------内功系统--------------------------------
	NEIGONG_INFO_UPDATE = "NEIGONG_INFO_UPDATE";
	NEIGONG_FIND_UPDATE = "NEIGONG_FIND_UPDATE";
	NEIGONG_UPGRADE_EVENT = "NEIGONG_UPGRADE_EVENT";
	NEIGONG_EXTRA_AWARD = "NEIGONG_EXTRA_AWARD";
	----------------------------------王府夺宝---------------------------------------
	WANGFU_SNATCH_RANK_UPDATE = "WANGFU_SNATCH_RANK_UPDATE";
	WANGFU_SNATCH_RIGHTTOP_UPDATE = "WANGFU_SNATCH_RIGHTTOP_UPDATE";
	WANGFU_SNATCH_TOP_UPDATE = "WANGFU_SNATCH_TOP_UPDATE";
	WANGFU_SNATCH_LEAVE_TIME = "WANGFU_SNATCH_LEAVE_TIME";
	----------------------------------运营活动----------------------------------
	OPERATION_ACTIVITY_TIME_UPDATE = "OPERATION_ACTIVITY_TIME_UPDATE";
	OPERATION_ACTIVITY_DATA_UPDATE = "OPERATION_ACTIVITY_DATA_UPDATE";
	OPERATION_ACTIVITY_AWARD_UPDATE = "OPERATION_ACTIVITY_AWARD_UPDATE";
	OPERATION_ACTIVITY_OPEN_FUNC = "OPERATION_ACTIVITY_OPEN_FUNC";
	DOUBLE_ACTIVITY_OPEN_FUNC = "DOUBLE_ACTIVITY_OPEN_FUNC";
	---------------------------------皇城修炼-----------------------------------
	IMPERIAL_CITY_PARCTICE_SCENE_STATE = "IMPERIAL_CITY_PARCTICE_SCENE_STATE";
	IMPERIAL_CITY_PARCTICE_AREA = "IMPERIAL_CITY_PARCTICE_AREA";
	IMPERIAL_CITY_PARCTICE_INFO_UPDATE = "IMPERIAL_CITY_PARCTICE_INFO_UPDATE";
	IMPERIAL_CITY_PARCTICE_CONFIRM = "IMPERIAL_CITY_PARCTICE_CONFIRM";
	IMPERIAL_CITY_PARCTICE_INVITE = "IMPERIAL_CITY_PARCTICE_INVITE";
	-------------------------------充值返利-------------------------------------
	RECHARGE_REBATE_YUANBAO = "RECHARGE_REBATE_YUANBAO";
	-------------------------------狂送元宝----------------------------------
	KUANGSONGYUANBAO_REQUEST_DATA = "KUANGSONGYUANBAO_REQUEST_DATA";
	KUANGSONGYUANBAO_BUY_YUANBAO = "KUANGSONGYUANBAO_BUY_YUANBAO";
	KUANGSONGYUANBAO_BUY_TIPS = "KUANGSONGYUANBAO_BUY_TIPS";
	---------------------------------野外boss--------------------------------------
	FIELD_BOSS_DATA_LIST = "FIELD_BOSS_DATA_LIST";
	FIELD_BOSS_DATA_ONE = "FIELD_BOSS_DATA_ONE";
	FIELD_BOSS_AFFILIATION_RANK = "FIELD_BOSS_AFFILIATION_RANK";
	----------------------------------寻宝------------------------------------
	TREASURE_MY_INFO_EVENT = "TREASURE_MY_INFO_EVENT";
	TREASURE_ALL_INFO_EVENT = "TREASURE_ALL_INFO_EVENT";
	TREASURE_AWARD_DATA_EVENT = "TREASURE_AWARD_DATA_EVENT";
	TREASURE_INTEGRAL_EXCHANGE = "TREASURE_INTEGRAL_EXCHANGE";
	TREASURE_INTEGRAL_UPDATE = "TREASURE_INTEGRAL_UPDATE";
	TREASURE_WARE_HOUSE_DATA = "TREASURE_WARE_HOUSE_DATA";
	-----------------------------------科举考试--------------------------------
	IMPERIAL_EXAM_STATE_EVENT = "IMPERIAL_EXAM_STATE_EVENT";
	IMPERIAL_EXAM_RANK_EVENT = "IMPERIAL_EXAM_RANK_EVENT";
	IMPERIAL_EXAM_RIGHT_TOP_UPDATE = "IMPERIAL_EXAM_RIGHT_TOP_UPDATE";
	IMPERIAL_EXAM_ENDING_EVENT = "IMPERIAL_EXAM_ENDING_EVENT";
	IMPERIAL_EXAM_QUESTION_EVENT = "IMPERIAL_EXAM_QUESTION_EVENT";
	IMPERIAL_EXAM_ANSWER_EVENT = "IMPERIAL_EXAM_ANSWER_EVENT";
	-----------------------------------幸运宝箱----------------------------------
	LUCKY_BOX_INFO_EVENT = "LUCKY_BOX_INFO_EVENT";
	LUCKY_BOX_RESULT_EVENT = "LUCKY_BOX_RESULT_EVENT";
	-----------------------------------七彩扭蛋----------------------------------
	COLOR_EGG_INFO_EVENT = "COLOR_EGG_INFO_EVENT";
	COLOR_EGG_RESULT_EVENT = "COLOR_EGG_RESULT_EVENT";
	-----------------------------------幸运砸蛋----------------------------------
	LUCKY_EGG_INFO_EVENT = "LUCKY_EGG_INFO_EVENT";
	LUCKY_EGG_REFRESH_EVENT = "LUCKY_EGG_REFRESH_EVENT";
	LUCKY_EGG_HISTORY_EVENT = "LUCKY_EGG_HISTORY_EVENT";
	--------------------------------剧情跳---------------------------------
	PLOT_JUMP_EVENT = "PLOT_JUMP_EVENT";

	-----------------------------活动开启---------------------------
	ACTIVITY_OPEN = "ACTIVITY_OPEN";

	-------------------------返利大厅-----------------------------
	REBATEAC_UI_BAR = "REBATEAC_UI_BAR";
	REBATEAC_UPSTEP = "REBATEAC_UPSTEP_INFO";
	REBATEAC_RECHARGE = "REBATEAC_RECHARGE_INFO";
	REBATEAC_DISCOUNTSHOP = "REBATEAC_RECHARGE_GET";
	REBATEAC_SINGLE_RECHARGE = "REBATEAC_SINGLE_RECHARGE";
	REBATEAC_ACCUMULATIVE_RECHARGE = "REBATEAC_ACCUMULATIVE_RECHARGE";
	REBATEAC_REPETITION_RECHARGE = "REBATEAC_REPETITION_RECHARGE";
	REBATEAC_CONTINUE_RECHARGE = "REBATEAC_CONTINUE_RECHARGE";
	REBATEAC_REPETITION_CONSUME = "REBATEAC_REPETITION_CONSUME";
	REBATEAC_CONTINUE_RECHARGE_GET = "REBATEAC_CONTINUE_RECHARGE_GET";

	-------------------------------采集------------------------------------
	UI_CAIJI_CANCEL = "caiji";

	-----------------------------精彩活动----------------------------------
	WONDERFUL_TAB = "WONDERFUL_TAB";
	WONDERFUL_RANKINGINFO = "WONDERFUL_RANKINGINFO";
	WONDERFUL_PANELINFO = "WONDERFUL_PANELINFO";

	-----------------------------投资计划--------------------------
	INVESTPLAB_INFO_CALLBACK = "INVESTPLAB_INFO_CALLBACK";

	-----------------------------霸装----
	BAZHUANG_INFO_CALLBACK = "BAZHUANG_INFO_CALLBACK";
	BAZHUANG_UNLOAD_CALLBACK = "BAZHUANG_UNLOAD_CALLBACK";
	BAZHUANG_REPLACE_CALLBACK = "BAZHUANG_REPLACE_CALLBACK";

	------------------------姻缘
	MARRIAGE_BANDQUET = "MARRIAGE_BANDQUET";
	MARRIAGE_CITYPARCTICE = "MARRIAGE_CITYPARCTICE";
	MARRIAGE_CAIJITYPE = "MARRIAGE_CAIJITYPE";
	MARRIAGE_CAIJICLICK = "MARRIAGE_CAIJICLICK";
	MARRIAGE_RINGINFO = "MARRIAGE_RINGINFO";
	MARRIAGE_TREEINFO = "MARRIAGE_TREEINFO";
	MARRIAGE_LINEINFO = "MARRIAGE_LINEINFO";
	MARRIAGE_TASKINFO = "MARRIAGE_TASKINFO";
	MARRIAGE_LINEINFO = "MARRIAGE_LINEINFO";
	MARRIAGE_LINE_START = "MARRIAGE_LINE_START";
	MARRIAGE_LINT_CHART = "MARRIAGE_LINT_CHART";
	MARRIAGE_LINE_CHOOSE = "MARRIAGE_LINE_CHOOSE";
	MARRIAGE_LINE_CHOOSE_STATE = "MARRIAGE_LINE_CHOOSE_STATE";
	MARRIAGE_LINE_CHOOSE_RESULT = "MARRIAGE_LINE_CHOOSE_RESULT";
	MARRIAGE_LINE_OVER = "MARRIAGE_LINE_OVER";
	MARRIAGE_CALLMATE = "MARRIAGE_CALLMATE";
	MARRIAGE_AREAININ = "MARRIAGE_AREAININ";
	MARRIAGE_WISHLIST = "MARRIAGE_WISHLIST";
	MARRIAGE_SENDHB = "MARRIAGE_SENDHB";
	MARRIAGE_SENDSWEET = "MARRIAGE_SENDSWEET";
	MARRIAGE_HB = "MARRIAGE_HB";
	MARRIAGE_GET_HB = "MARRIAGE_GET_HB";
	SHENXIANJUANLV_ICON = "SHENXIANJUANLV_ICON";
	---------------------------杀戮战场----------------------------
	KILLING_FIELDS_RANK_THREE = "KILLING_FIELDS_RANK_THREE";
	KILLING_FIELDS_TOP_INFO = "KILLING_FIELDS_TOP_INFO";
	KILLING_FIELDS_SELF_INTEGRAL = "KILLING_FIELDS_SELF_INTEGRAL";
	KILLING_FIELDS_ENDING = "KILLING_FIELDS_ENDING";
	KILLING_FIELDS_RANK = "KILLING_FIELDS_RANK";

	-------------------- 战斗 --------------------
	FIGHT_TARGET_CHANGED = "FIGHT_TARGET_CHANGED";
	----------------------节日BOSS------------------------
	JIERIBOSS_MAINICON = "JIERIBOSS_MAINICON";
	JIERIBOSS_UIINFO = "JIERIBOSS_UIINFO";
	JIERIBOSS_DAMAGERANK = "JIERIBOSS_DAMAGERANK";
	JIERIBOSS_ENDREWARD = "JIERIBOSS_ENDREWARD";
	JIERIBOSS_RANKFIVE = "JIERIBOSS_RANKFIVE";
	JIERIBOSS_RANK = "JIERIBOSS_RANK";
	JIERIBOSS_BOSSHP = "JIERIBOSS_BOSSHP";
	JIERIBOSS_ISOK = "JIERIBOSS_ISOK";
	JIERIBOSS_SCENETIME = "JIERIBOSS_SCENETIME";
	-------------------------跨服夺宝---------------------------
	CROSS_TREASURE_BASE_INFO = "CROSS_TREASURE_BASE_INFO";
	CROSS_TREASURE_SELF_HISTORY = "CROSS_TREASURE_SELF_HISTORY";
	CROSS_TREASURE_HUNT_AWARD = "CROSS_TREASURE_HUNT_AWARD";
	CROSS_TREASURE_INTEGRAL_SHOP = "CROSS_TREASURE_INTEGRAL_SHOP";
	CROSS_TREASURE_INTEGRAL_HISTORY = "CROSS_TREASURE_INTEGRAL_HISTORY";
---------------------------帮派秘境-------------------------------
	BH_MIJING_INFO = "BH_MIJING_INFO";
	BH_MIJING_RANK_UPDATE = "BH_MIJING_RANK_UPDATE";

---------------------------主界面事件-------------------------------
	MAIN_PANEL_BOTTOME_EVENT = "MAIN_PANEL_BOTTOME_EVENT";

----------------------BOSS密境-----------------------
	SECRETBOSS_BELONG = "SECRETBOSS_BELONG";
	SECRETBOSS_INFO = "SECRETBOSS_INFO";
	SECRETBOSS_FRESH = "SECRETBOSS_FRESH";
	SECRETBOSS_TIRED = "SECRETBOSS_TIRED";
------------------------幻形激活-------------------
	METAMORPHSIS_ACTIVE = "METAMORPHSIS_ACTIVE";
}