--($Id)
--该文件为代码自动生成，请不要手动修改

local Data = 
{
	[10202001] = {
		["NeedGrade"] = 15,
		["Price"] = 100,
		["Step"] = 1,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 2,
		["FitEquip"] = { [1] = 2,		},
		["GetPath"] = "副本",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10202001,
		["Name"] = "寒冰戒指",
		["IconNo"] = 400003,
		["Rare"] = 3,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10201008] = {
		["NeedGrade"] = 22,
		["Price"] = 107,
		["Step"] = 8,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201008,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 6,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10102001] = {
		["AtlasPath"] = "",
		["GetPath"] = "经验副本、江湖试炼、野外杀怪",
		["Price"] = 0,
		["Step"] = 3,
		["CanUse"] = 1,
		["CanDrop"] = 1,
		["VIP"] = 0,
		["SubKind"] = 2,
		["CanBatch"] = 1,
		["NeedGrade"] = 1,
		["RelaKey"] = {BindYuanBao=1},
		["Info"] = "[435B74]使用后获得绑定元宝[-]",
		["ItemNo"] = 10102001,
		["Rare"] = 4,
		["NickName"] = "",
		["CanArrange"] = 2,
		["AddIcon"] = "",
		["Name"] = "绑定元宝",
		["IconNo"] = 406007,
		["IconStr"] = "",
		["Kind"] = 1,
		["UiId"] = {		},
		["frame"] = 1,
	},
	[10201009] = {
		["NeedGrade"] = 23,
		["Price"] = 108,
		["Step"] = 9,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201009,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 6,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10102002] = {
		["AtlasPath"] = "",
		["NeedGrade"] = 1,
		["Price"] = 0,
		["ItemNo"] = 10102002,
		["CanUse"] = 1,
		["CanDrop"] = 1,
		["VIP"] = 0,
		["SubKind"] = 2,
		["RelaKey"] = {ToGrade={59,48000000}},
		["GetPath"] = "VIP礼包",
		["Step"] = 4,
		["Rare"] = 4,
		["NickName"] = "",
		["UiId"] = {		},
		["AddIcon"] = "",
		["Name"] = "人物升级丹",
		["IconNo"] = 404127,
		["IconStr"] = "",
		["frame"] = 1,
		["Info"] = "[435B74]59级以下（包括59级）使用可直接提升一级。\\n高于59级使用可获得经验 * 48000000。[-]",
		["Kind"] = 1,
	},
	[10201010] = {
		["NeedGrade"] = 24,
		["Price"] = 109,
		["Step"] = 10,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201010,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 6,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10102003] = {
		["AtlasPath"] = "",
		["GetPath"] = "神器副本",
		["Price"] = 30,
		["Step"] = 3,
		["CanUse"] = 1,
		["CanDrop"] = 1,
		["VIP"] = 0,
		["SubKind"] = 3,
		["CanBatch"] = 1,
		["NeedGrade"] = 1,
		["RelaKey"] = {Lingqi=1},
		["Info"] = "[435B74]使用后获得1点灵气[-]",
		["ItemNo"] = 10102003,
		["Rare"] = 3,
		["NickName"] = "",
		["CanArrange"] = 2,
		["AddIcon"] = "",
		["Name"] = "灵气丹",
		["IconNo"] = 404082,
		["IconStr"] = "",
		["Kind"] = 1,
		["UiId"] = {		},
		["frame"] = 1,
	},
	[10199001] = {
		["NeedGrade"] = 1,
		["Price"] = 0,
		["ItemNo"] = 10199001,
		["CanUse"] = 1,
		["CanDrop"] = 1,
		["VIP"] = 0,
		["SubKind"] = 99,
		["CanBatch"] = 1,
		["Step"] = 3,
		["GetPath"] = "帮派任务、帮派BOSS",
		["AddIcon"] = "",
		["Rare"] = 3,
		["NickName"] = "",
		["OverLap"] = 9999,
		["frame"] = 1,
		["Name"] = "帮贡",
		["IconNo"] = 406020,
		["IconStr"] = "",
		["Kind"] = 1,
		["UiId"] = {		},
		["Info"] = "[435B74]用于对帮派做出杰出贡献的成员的奖赏，可以用于升级帮派技能。[-]",
	},
	[10201004] = {
		["NeedGrade"] = 18,
		["Price"] = 103,
		["Step"] = 4,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201004,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 6,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10102999] = {
		["AtlasPath"] = "",
		["GetPath"] = "七日登录、礼包",
		["Price"] = 0,
		["Step"] = 3,
		["CanUse"] = 1,
		["CanDrop"] = 1,
		["VIP"] = 0,
		["SubKind"] = 2,
		["CanBatch"] = 1,
		["NeedGrade"] = 1,
		["RelaKey"] = {YuanBao=1},
		["Info"] = "[435B74]使用后获得元宝[-]",
		["ItemNo"] = 10102999,
		["Rare"] = 4,
		["NickName"] = "",
		["CanArrange"] = 2,
		["AddIcon"] = "",
		["Name"] = "元宝",
		["IconNo"] = 406001,
		["IconStr"] = "",
		["Kind"] = 1,
		["UiId"] = {		},
		["frame"] = 1,
	},
	[10201005] = {
		["NeedGrade"] = 19,
		["Price"] = 104,
		["Step"] = 5,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201005,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 3,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10201006] = {
		["NeedGrade"] = 20,
		["Price"] = 105,
		["Step"] = 6,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201006,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 4,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10201002] = {
		["NeedGrade"] = 16,
		["Price"] = 101,
		["Step"] = 2,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201002,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 4,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10201007] = {
		["NeedGrade"] = 21,
		["Price"] = 106,
		["Step"] = 7,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201007,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 5,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10201003] = {
		["NeedGrade"] = 17,
		["Price"] = 102,
		["Step"] = 3,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201003,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 5,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
	[10201001] = {
		["NeedGrade"] = 15,
		["Price"] = 100,
		["Step"] = 1,
		["CanUse"] = 0,
		["CanDrop"] = 0,
		["SubKind"] = 1,
		["FitEquip"] = { [1] = 1,		},
		["GetPath"] = "副本",
		["NickName"] = "",
		["OverLap"] = 1,
		["ItemNo"] = 10201001,
		["Name"] = "冰冥剑",
		["IconNo"] = 400009,
		["Rare"] = 3,
		["Kind"] = 2,
		["Info"] = "百炼精钢所制，剑身厚重有力，可斩金断铁。",
		["frame"] = 2,
	},
}

return Data
