//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ChatVoiceServiceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ChatVoiceService), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetSoundRecogonizeString", GetSoundRecogonizeString);
		L.RegFunction("StartRecordSound", StartRecordSound);
		L.RegFunction("EndRecordSound", EndRecordSound);
		L.RegFunction("GetVoice", GetVoice);
		L.RegFunction("YuYinClick", YuYinClick);
		L.RegFunction("StopPlayYuyin", StopPlayYuyin);
		L.RegFunction("RemoveYuYinData", RemoveYuYinData);
		L.RegFunction("GetYuYinDataBySn", GetYuYinDataBySn);
		L.RegFunction("CheckMicrophonePermission", CheckMicrophonePermission);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("_audioSource", get__audioSource, set__audioSource);
		L.RegVar("curShowPanel", get_curShowPanel, set_curShowPanel);
		L.RegVar("chatCanvas", get_chatCanvas, set_chatCanvas);
		L.RegVar("chatWnd", get_chatWnd, set_chatWnd);
		L.RegVar("chatUi", get_chatUi, set_chatUi);
		L.RegVar("Instance", get_Instance, null);
		L.RegVar("curPrivateCharId", get_curPrivateCharId, set_curPrivateCharId);
		L.RegVar("curPrivateCharUid", get_curPrivateCharUid, set_curPrivateCharUid);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSoundRecogonizeString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
			string o = obj.GetSoundRecogonizeString(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartRecordSound(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			obj.StartRecordSound();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EndRecordSound(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.EndRecordSound(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetVoice(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			float o = obj.GetVoice();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int YuYinClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.YuYinClick(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopPlayYuyin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			obj.StopPlayYuyin();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveYuYinData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			string arg0 = ToLua.CheckString(L, 2);
			obj.RemoveYuYinData(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetYuYinDataBySn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.GetYuYinDataBySn(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CheckMicrophonePermission(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ChatVoiceService obj = (ChatVoiceService)ToLua.CheckObject(L, 1, typeof(ChatVoiceService));
			string arg0 = ToLua.CheckString(L, 2);
			obj.CheckMicrophonePermission(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get__audioSource(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			UnityEngine.AudioSource ret = obj._audioSource;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _audioSource on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_curShowPanel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			int ret = obj.curShowPanel;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curShowPanel on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_chatCanvas(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			UnityEngine.Transform ret = obj.chatCanvas;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index chatCanvas on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_chatWnd(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			UnityEngine.Transform ret = obj.chatWnd;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index chatWnd on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_chatUi(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			UnityEngine.Transform ret = obj.chatUi;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index chatUi on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, ChatVoiceService.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_curPrivateCharId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			int ret = obj.curPrivateCharId;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curPrivateCharId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_curPrivateCharUid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			string ret = obj.curPrivateCharUid;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curPrivateCharUid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set__audioSource(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			UnityEngine.AudioSource arg0 = (UnityEngine.AudioSource)ToLua.CheckObject(L, 2, typeof(UnityEngine.AudioSource));
			obj._audioSource = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index _audioSource on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_curShowPanel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.curShowPanel = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curShowPanel on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_chatCanvas(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
			obj.chatCanvas = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index chatCanvas on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_chatWnd(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
			obj.chatWnd = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index chatWnd on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_chatUi(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
			obj.chatUi = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index chatUi on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_curPrivateCharId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.curPrivateCharId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curPrivateCharId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_curPrivateCharUid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ChatVoiceService obj = (ChatVoiceService)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.curPrivateCharUid = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curPrivateCharUid on a nil value");
		}
	}
}

