//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EndlessCellWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(EndlessCell), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("UpdateTableItem", UpdateTableItem);
		L.RegFunction("OnClick", OnClick);
		L.RegFunction("IsPointOverItemCell", IsPointOverItemCell);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateTableItem(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			EndlessCell obj = (EndlessCell)ToLua.CheckObject<EndlessCell>(L, 1);
			obj.UpdateTableItem();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			EndlessCell obj = (EndlessCell)ToLua.CheckObject<EndlessCell>(L, 1);
			obj.OnClick();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsPointOverItemCell(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EndlessCell obj = (EndlessCell)ToLua.CheckObject<EndlessCell>(L, 1);
			UnityEngine.Vector3 arg0 = ToLua.ToVector3(L, 2);
			bool o = obj.IsPointOverItemCell(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

