//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MultiRowWrapContentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MultiRowWrapContent), typeof(UIWrapContent));
		L.RegFunction("SortBasedOnScrollMovement", SortBasedOnScrollMovement);
		L.RegFunction("WrapContent", WrapContent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("RowNum", get_RowNum, set_RowNum);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SortBasedOnScrollMovement(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MultiRowWrapContent obj = (MultiRowWrapContent)ToLua.CheckObject<MultiRowWrapContent>(L, 1);
			obj.SortBasedOnScrollMovement();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int WrapContent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MultiRowWrapContent obj = (MultiRowWrapContent)ToLua.CheckObject<MultiRowWrapContent>(L, 1);
			obj.WrapContent();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RowNum(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MultiRowWrapContent obj = (MultiRowWrapContent)o;
			int ret = obj.RowNum;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RowNum on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RowNum(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			MultiRowWrapContent obj = (MultiRowWrapContent)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.RowNum = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RowNum on a nil value");
		}
	}
}

